spring:
  application:
    name: gyma
  datasource:
    url: jdbc:postgresql://localhost:5432/gymaintegrador
    username: postgres
    password: pgadmin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    org:
      springframework:
        web: DEBUG
        security: DEBUG
server:
  # Back-end (8081) e Keycloak (8080)
  port: 8081
springdoc:
  override-with-generic-response: false