# SPRING CONFIGS
spring:
  application:
    name: gyma
  datasource:
    url: jdbc:postgresql://localhost:5432/gyma
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: gyma_spring
            client-secret: BQ9VSM4SMrlRoY11olsJVsiZNExUVAhC
            scope: openid, profile, email
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8081/login/oauth2/code/keycloak
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/gyma
# END SPRING CONFINGS

# LOGGING
logging:
  level:
    org:
      springframework:
        web: DEBUG
        security: TRACE
        boot:
          actuate: DEBUG
        io.micrometer: DEBUG
# END LOGGING

# SERVER
# Back-end (8081) e Keycloak (8080)
server:
  port: 8081
# END SERVER

# SWAGGER
springdoc:
  override-with-generic-response: false
# END SWAGGER

# GRAFANA
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "health,info,prometheus"
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
    prometheus:
      enabled: true
# END GRAFANA/PROMETHEUS