spring:
  application:
    name: gyma
  datasource:
    url: jdbc:postgresql://localhost:5432/gyma
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/gyma
          jwk-set-uri: http://localhost:8080/realms/gyma/protocol/openid-connect/certs
logging:
  level:
    org:
      springframework:
        web: DEBUG
        security: DEBUG
server:
  port: 8081
springdoc:
  override-with-generic-response: false
keycloak:
  auth-server-url: http://localhost:8080
  realm: gyma
  resource: gyma_spring
  credentials:
    secret: SafLxP65rp0nXhHgUP3Qi2vm4H0cIMut
  public-client: false
  use-resource-role-mappings: true
  bearer-only: true
  ssl-required: external
  cookie:
    path: /
  cors: true

