name: Java CI with Maven

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: List files
        run: ls -R ./gyma

      - name: Validate Maven setup
        working-directory: ./gyma
        run: mvn validate

      - name: Build with Maven
        working-directory: ./gyma
        run: mvn clean install -DskipTests -e

      - name: Run tests
        working-directory: ./gyma
        run: mvn test -e
