name: Deploy

on:
  push:
    branches: [dev]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: List files
        run: ls -R ./gyma

      - name: Build with Maven
        working-directory: ./gyma
        run: mvn clean install -DskipTests -e

      - name: Run tests
        working-directory: ./gyma
        run: mvn test -e

      - name: Build docker image
        run: docker build -t gyma:latest ./gyma

      - name: Stop existing container (if any)
        run: |
          docker stop gyma-container || true
          docker rm gyma-container || true

      - name: Run Docker Container
        run: docker run -d --name gyma-container gyma:latest
