name: Deploy

on:
  push:
    branches: [dev]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: List files
        run: ls -R ./gyma

      - name: Build with Maven
        working-directory: ./gyma
        run: mvn clean install -DskipTests -e

      - name: Run tests
        working-directory: ./gyma
        run: mvn test -Dspring.profiles.active=test -e

      - name: Build docker image
        run: docker build -t gyma:latest ./gyma

      #- name: Stop existing containers (if any)
      #  run: |
      #    docker-compose -f ./gyma/docker-compose.yml down || true

     # - name: Run Docker Compose
     #   run: |
     #     docker-compose --env-file ./gyma/.env -f ./gyma/docker-compose.yml up -d

